<<<<<<< HEAD
language: python

install:
 - pip install -r requirement.txt

script:
 - pytest

=======
language: node_js

node_js:
 - 12
        
before_install:
 - cd myapp/
        
install:
 - npm install
        
script:
 - npm run build
>>>>>>> 6438cc9a23a8f366b7b5ef30d9833cb6ffe54cec
