matrix:
  inlcude:
    - language: python
      install:
        - pip install -r requirement.txt

      script:
         - pytest

    - language: node_js
      node_js: "14"
        
      before_install:
        - cd myapp/
        
      install:
        - npm install
        
       script:
        - npm run build
